//   'AngelList' : 'AL',         y
//   'BetaList' : 'BL',
//   'Company Website': 'C',
//   'CareerBuilder' : 'CB',
//   'Dice' : 'D',               y
//   'GlassDoor' : 'GD',
//   'Indeed' : 'I',
//   'LinkedIn' : 'LI',          n
//   'LinkUp' : 'LU',
//   'Monster' : 'M',
//   'Referral' : 'R',
//   'SmartRecruiters' : 'SR',
//   'We Work Remotely' : 'WWR',
//   'ZipRecruiter': 'ZR',
//
//   'lever'                     y

export const sources = {
  'a' : [['AngelList', 'AL']],
  'al' : [['AngelList', 'AL']],
  'an' : [['AngelList', 'AL']],
  'ang' : [['AngelList', 'AL']],
  'ange' : [['AngelList', 'AL']],
  'angel' : [['AngelList', 'AL']],
  'angell' : [['AngelList', 'AL']],
  'angelli' : [['AngelList', 'AL']],
  'angellis' : [['AngelList', 'AL']],
  'angellist' : [['AngelList', 'AL']],
  'b' : [['BetaList', 'BL']],
  'bl' : [['BetaList', 'BL']],
  'be' : [['BetaList', 'BL']],
  'bet' : [['BetaList', 'BL']],
  'beta' : [['BetaList', 'BL']],
  'betal' : [['BetaList', 'BL']],
  'betali' : [['BetaList', 'BL']],
  'betalis' : [['BetaList', 'BL']],
  'betalist' : [['BetaList', 'BL']],
  'c' : [['Company Website', 'C'], ['CareerBuilder', 'CB']],
  'co' : [['Company Website', 'C']],
  'com' : [['Company Website', 'C']], 
  'comp' : [['Company Website', 'C']], 
  'compa' : [['Company Website', 'C']], 
  'compan' : [['Company Website', 'C']], 
  'company' : [['Company Website', 'C']], 
  'company ' : [['Company Website', 'C']], 
  'company w' : [['Company Website', 'C']], 
  'company we' : [['Company Website', 'C']], 
  'company web' : [['Company Website', 'C']], 
  'company webs' : [['Company Website', 'C']], 
  'company websi' : [['Company Website', 'C']], 
  'company websit' : [['Company Website', 'C']], 
  'company website' : [['Company Website', 'C']], 
  'cb' : [['CareerBuilder', 'CB']],
  'ca' : [['CareerBuilder', 'CB']],
  'car' : [['CareerBuilder', 'CB']],
  'care' : [['CareerBuilder', 'CB']],
  'caree' : [['CareerBuilder', 'CB']],
  'career' : [['CareerBuilder', 'CB']],
  'careerb' : [['CareerBuilder', 'CB']],
  'careerbu' : [['CareerBuilder', 'CB']],
  'careerbui' : [['CareerBuilder', 'CB']],
  'careerbuil' : [['CareerBuilder', 'CB']],
  'careerbuild' : [['CareerBuilder', 'CB']],
  'careerbuilde' : [['CareerBuilder', 'CB']],
  'careerbuilder' : [['CareerBuilder', 'CB']],
  'd' : [['Dice', 'D']],
  'di' : [['Dice', 'D']],
  'dic' : [['Dice', 'D']],
  'dice' : [['Dice', 'D']],
  'g' : [['GlassDoor', 'GD']],
  'gd' : [['GlassDoor', 'GD']],
  'gl' : [['GlassDoor', 'GD']],
  'gla' : [['GlassDoor', 'GD']],
  'glas' : [['GlassDoor', 'GD']],
  'glass' : [['GlassDoor', 'GD']],
  'glassd' : [['GlassDoor', 'GD']],
  'glassdo' : [['GlassDoor', 'GD']],
  'glassdoo' : [['GlassDoor', 'GD']],
  'glassdoor' : [['GlassDoor', 'GD']],
  'i' : [['Indeed', 'I']],
  'in' : [['Indeed', 'I']],
  'ind' : [['Indeed', 'I']],
  'inde' : [['Indeed', 'I']],
  'indee' : [['Indeed', 'I']],
  'indeed' : [['Indeed', 'I']],
  'l' : [['LinkedIn', 'LI'], ['LinkUp', 'LU']],
  'li' : [['LinkedIn', 'LI'], ['LinkUp', 'LU']],
  'lin' : [['LinkedIn', 'LI'], ['LinkUp', 'LU']],
  'link' : [['LinkedIn', 'LI'], ['LinkUp', 'LU']],
  'linke' : [['LinkedIn', 'LI']],
  'linked' : [['LinkedIn', 'LI']],
  'linkedI' : [['LinkedIn', 'LI']],
  'linkedIn' : [['LinkedIn', 'LI']],
  'lu' : [['LinkUp', 'LU']],
  'linku' : [['LinkUp', 'LU']],
  'linkup' : [['LinkUp', 'LU']],
  'm' : [['Monster', 'M']],
  'mo' : [['Monster', 'M']],
  'mon' : [['Monster', 'M']],
  'mons' : [['Monster', 'M']],
  'monst' : [['Monster', 'M']],
  'monste' : [['Monster', 'M']],
  'monster' : [['Monster', 'M']],
  'r' : [['Referral', 'R']],
  're' : [['Referral', 'R']],
  'ref' : [['Referral', 'R']],
  'refe' : [['Referral', 'R']],
  'refer' : [['Referral', 'R']],
  'referr' : [['Referral', 'R']],
  'referra' : [['Referral', 'R']],
  'referral' : [['Referral', 'R']],
  's' : [['SmartRecruiters', 'SR']],
  'sr' : [['SmartRecruiters', 'SR']],
  'sm' : [['SmartRecruiters', 'SR']],
  'sma' : [['SmartRecruiters', 'SR']],
  'smar' : [['SmartRecruiters', 'SR']],
  'smart' : [['SmartRecruiters', 'SR']],
  'smartr' : [['SmartRecruiters', 'SR']],
  'smartre' : [['SmartRecruiters', 'SR']],
  'smartrec' : [['SmartRecruiters', 'SR']],
  'smartrecr' : [['SmartRecruiters', 'SR']],
  'smartrecru' : [['SmartRecruiters', 'SR']],
  'smartrecrui' : [['SmartRecruiters', 'SR']],
  'smartrecruit' : [['SmartRecruiters', 'SR']],
  'smartrecruite' : [['SmartRecruiters', 'SR']],
  'smartrecruiter' : [['SmartRecruiters', 'SR']],
  'smartrecruiters' : [['SmartRecruiters', 'SR']],
  'w' : [['We Work Remotely', 'WWR']],
  'ww' : [['We Work Remotely', 'WWR']],
  'wwr' : [['We Work Remotely', 'WWR']],
  'we' : [['We Work Remotely', 'WWR']],
  'we ' : [['We Work Remotely', 'WWR']],
  'we w' : [['We Work Remotely', 'WWR']],
  'we wo' : [['We Work Remotely', 'WWR']],
  'we wor' : [['We Work Remotely', 'WWR']],
  'we work' : [['We Work Remotely', 'WWR']],
  'we work ' : [['We Work Remotely', 'WWR']],
  'we work r' : [['We Work Remotely', 'WWR']],
  'we work re' : [['We Work Remotely', 'WWR']],
  'we work rem' : [['We Work Remotely', 'WWR']],
  'we work remo' : [['We Work Remotely', 'WWR']],
  'we work remot' : [['We Work Remotely', 'WWR']],
  'we work remotl' : [['We Work Remotely', 'WWR']],
  'we work remotle' : [['We Work Remotely', 'WWR']],
  'we work remotely' : [['We Work Remotely', 'WWR']],
  'z' : [['ZipRecruiter', 'ZR']],
  'zi' : [['ZipRecruiter', 'ZR']],
  'zip' : [['ZipRecruiter', 'ZR']],
  'zipr' : [['ZipRecruiter', 'ZR']],
  'zipre' : [['ZipRecruiter', 'ZR']],
  'ziprec' : [['ZipRecruiter', 'ZR']],
  'ziprecr' : [['ZipRecruiter', 'ZR']],
  'ziprecru' : [['ZipRecruiter', 'ZR']],
  'ziprecrui' : [['ZipRecruiter', 'ZR']],
  'ziprecruit' : [['ZipRecruiter', 'ZR']],
  'ziprecruite' : [['ZipRecruiter', 'ZR']],
  'ziprecruiter' : [['ZipRecruiter', 'ZR']],
}
